version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@marketplace.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend-api-rest:
    container_name: api-marketplace
    build:
      context: api-marketplace
    ports:
      - '3000:3000'
    restart: always
    # depends_on:
    #   - postgres

      
  frontend-react:
    container_name: ui-marketplace
    build:
      context: ui-marketplace
    ports:
      - '4000:80'
    restart: always


volumes:
  postgres_data:
