version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL:  
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend-api-rest:
    build:
      context: Backend
    ports:
      - '3001:3001'
    restart: always
    environment:
      - NODE_ENV=production
  #   # command: sh -c "npx sequelize-cli db:migrate && node index.js"
      
  frontend-react:
    build:
      context: Front
    ports:
      - '4000:80'
    restart: always


volumes:
  postgres_data:
